
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Jan 03 23:21:28 CET 2025
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MAP = 19;
  public static final int LTE = 44;
  public static final int LBRACKET = 13;
  public static final int CONST = 9;
  public static final int CHAR = 3;
  public static final int LPAREN = 16;
  public static final int SEMI = 10;
  public static final int CONTINUE = 30;
  public static final int MINUS = 35;
  public static final int RPAREN = 17;
  public static final int AND = 22;
  public static final int LT = 43;
  public static final int OR = 21;
  public static final int BOOL = 5;
  public static final int COMMA = 12;
  public static final int INC = 23;
  public static final int DIV = 37;
  public static final int NUM = 4;
  public static final int PLUS = 34;
  public static final int ASSIGN = 11;
  public static final int IF = 25;
  public static final int DOT = 18;
  public static final int EOF = 0;
  public static final int RETURN = 31;
  public static final int RBRACKET = 14;
  public static final int NEW = 20;
  public static final int error = 1;
  public static final int MUL = 36;
  public static final int MOD = 38;
  public static final int NEQ = 40;
  public static final int BREAK = 29;
  public static final int IDENT = 2;
  public static final int VOID = 15;
  public static final int EQ = 39;
  public static final int GTE = 42;
  public static final int UNION = 45;
  public static final int LBRACE = 7;
  public static final int ELSE = 26;
  public static final int READ = 32;
  public static final int WHILE = 27;
  public static final int RBRACE = 8;
  public static final int PROG = 6;
  public static final int DEC = 24;
  public static final int GT = 41;
  public static final int PRINT = 33;
  public static final int DO = 28;
}

